--
-- Début du patch.sql généré par CompareSQL V1
--
--
-- Gestion des différences de structures de la BDD et des tables
--
--
-- Ajout des données supplémentaires
--
--
-- Suppression des données qui n'existent plus
--
