#!/bin/bash
# Script use to save the database collections

db="sxapi"
out_dir="/var/www/html/startx/api/.startx/db-dump"
tmp_file="tmp_file"
echo "print('_ ' + db.getCollectionNames())" > $tmp_file
cols=`mongo $db $tmp_file | grep '_' | awk '{print $2}' | tr ',' ' '`
rm $tmp_file
echo_prefix="[pre-commit hook]"

# execute doc-generate and comit-push to github
function dumpDatabases {
   echo -e "$echo_prefix Start dumping database"
   for c in $cols
    do
        if [[ $c != "logs" ]] && [[ $c != "startx.logs" ]] && [[ $c != "sxapi.session" ]] ; then
        echo -e "$echo_prefix Exporting $c "
        mongoexport -d $db -c $c -o "$out_dir/dump_${db}_${c}.json" --jsonArray &> /dev/null
        fi
   done
   git add $out_dir/*
   echo -e "$echo_prefix End dumping database"
}


echo -e "$echo_prefix Start pre-commit process"
# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty
while true; do
    read -p "$echo_prefix Do you wan't to dump database(s) ? (Y/n) " yn
    if [ "$yn" = "" ]; then
       yn='Y'
    fi
    case $yn in
       [Yy] ) dumpDatabases; exit 0;;
       [Nn] ) exit 0;;
       * ) echo -e "$echo_prefix Please answer y or n for yes or no.";;
    esac
done
echo -e "$echo_prefix End pre-commit process"
