#!/bin/sh

dir=`dirname $0`
echo "-- Génération de la documentation
read -p "-- Souhaitez-vous générer la documentation (y/n)?" CONT
if [ "$CONT" == "y" ]; then
    ( . $dir/../doc-generate )
fi
read -p "-- Souhaitez-vous pousser la documentation (y/n)?" CONT2
if [ "$CONT2" == "y" ]; then
    cd $dir/../../../api.wiki
    git commit -a -m "génération de la documentation"
    git push 
    cd -
fi
exit 0;