var ZTips = {
    authentification: {
	identifiant: 		'Votre identifiant vous a été communiqué lors de votre inscription',
	mdp: 			'Le mot de passe associé à votre identifiant vous a été communiqué lors de votre inscription'
    } ,

    contactEnt: {
	ajaxField: 		'Saisissez le début du nom d\'une entreprise, un code postal ou une ville pour obtenir la liste des entreprises corespondantes.<br/>La recherche se limite à 20 résultats.<br/> Vous devez cliquer sur le résultat choisi pour séléctionner l\'entreprise corespondante',
	nom: 			'<b>Raison sociale</b> de cette entreprise',
	type: 			'<b>Type de relation</b> que vous entretenez avec cette entreprise.<br/>Si vous choisissez <b>fournisseur</b>, cette entreprise pourra être enregistrée comme fournisseur dans la partie gestion des produits',
	web: 			'<b>Site web public</b> de cette entreprise',
	fax: 			'<b>Numéro de fax</b> de l\'entreprise. Ce numéro est utilisé par la suite, pour l\'envoi de document par fax.',
	tel: 			'<b>Numéro de téléphone du standard</b> de l\'entreprise.',
	cpVille: 		'Saisissez le <b>code postal</b> de l\'entreprise.<br/> Le <b>nom de la ville</b> apparait automatiquement. Vous pouvez cependant modifier la ville proposée, en modifiant le champs ville.',
	add: 			'<b>Adresse de l\'entreprise</b>. Ce champs est utilisé pour toute communication courrier avec cette entreprise.<br/>Veillez à saisir correctement les informations qui vous ont été transmises.',
	pays: 			'<b>Pays</b> de domiciliation de l\'entreprise',
	activite: 		'<b>Activité principale</b> de cette entreprise<br/> Permet de faire des recherches statistiques',
	effectif: 		'<b>Effectif</b> de cette entreprise.<br/> Permet de faire des recherches statistiques',
	groupe: 		'Cette entreprise fait-elle partie d\'<b>un groupe</b> ? Le choix s\'effectue sur toutes les entreprises présentes dans la base, et qui sont marquées comme étant un "siège social"',
	siege: 			'Cette entreprise est-elle <b>le siège social d\'un groupe</b> ? Si vous cochez cette case, vous aurez la possibilité de relier à cette entreprise les fiches entreprises des filiales.',
	nfourn: 		'<b>Votre numéro de fournisseur</b> auprès de cette entreprise.<br/>Si rempli, ce numéro est repris dans vos documents commerciaux afin de faciliter le traitement de vos corespondances.',
	nsiret: 		'Numero de <b>SIRET</b> de l\'entreprise.',
	ntva: 			'Numéro de <b>TVA Intracommunautaire</b>.<br/>Si rempli, ce numéro est repris dans vos documents commerciaux afin de faciliter le traitement de vos factures.',
	tva: 			'<b>Taux de TVA</b> applicable à cette entreprise.',
	remise: 		'Vous permet de définir un <b>taux de remise accordé</b> au niveau de l\'entreprise. Ce taux sera automatiquement proposé lors de la création de devis.',
	commentaire: 		'<b>Commentaire libre</b> vous permettant d\'ajouter un complément d\information concerant cette entreprise en particulier.'
    } ,
  
    contactPers: {
	ajaxField: 		'Saisissez le début du nom ou du prenom d\'un contact pour obtenir la liste des contacts corespondants.<br/>La recherche se limite à 20 résultats.<br/> Vous devez cliquer sur le résultat choisi pour séléctionner le contact correspondant',
	civ: 			'<b>Civilité</b> de votre contact',
	nom: 			'<b>Nom de famille</b> de ce contact.',
	prenom: 		'<b>Prenom</b> de ce contact.',
	fonction: 		'<b>Fonction</b> de ce contact.',
	web: 			'<b>Site web public</b> de ce contact.',
	fax: 			'<b>Numéro de fax</b> du contact. Ce numéro est utilisé par la suite, pour l\'envoi de document par fax.',
	tel: 			'<b>Numéro de téléphone</b> du contact.',
	mob: 			'<b>Numéro de portable</b> du contact.',
	mail: 			'Adresse <b>e-mail</b> du contact.',
	cpVille: 		'Saisissez le <b>code postal</b> du contact.<br/> Le <b>nom de la ville</b> apparait automatiquement. Vous pouvez cependant modifier la ville proposée, en modifiant le champs ville.',
	add: 			'<b>Adresse du contact</b>. Ce champs est utilisé pour toute communication courrier avec ce contact.<br/>Veillez à saisir correctement les informations qui vous ont été transmises.',
	pays:			'<b>Pays</b> de domiciliation du contact',
	entrepriseNom: 		'<b>Raison sociale</b> de l\'entreprise liée à ce contact',
	entrepriseType: 	'<b>Type</b> de l\'entreprise liée à cette fiche contact',
	entrepriseWeb: 		'<b>Site web public</b> de l\'entreprise liée à ce contact',
	commentaire: 		'<b>Commentaire libre</b> vous permettant d\'ajouter un complément d\information concernant ce contact en particulier.'
    } ,
  
    contacts: {
	searchCriteria: 	'<b>Critère de votre recherche</b>. Le texte saisi sera recherché dans les champs corespondant au type de recherche que vous avez choisi',
	searchType: 		'<b>Type de recherche</b><br/><ul><li>La recherche parmis les entreprises recherche sur les informations d\'entreprise uniquement</li><li>La recherche parmis les contacts recherche sur les informations des contacts uniquement</li><li>La recherche parmis les appels recherche sur les informations des appels passés</li><li>La recherche globale recherche sur l\'ensemble des informations</li></ul>',
	searchAppelDebut: 	'<b>Date de début</b><br/>Les appels séléctionnés ont une date d\'appel supérieure à la date fournie',
	searchAppelFin: 	'<b>Date de fin</b><br/>Les appels séléctionnés ont une date d\'appel inférieure à la date fournie',
	searchAppelRelancer:	'Les appels séléctionnés doivent avoir l\'option "à relancer" d\'activée pour apparaitre dans le résultat',
	searchAppelCommercial:	'<b>Commercial</b><br/>Seul les appels passés par ce commercial seront séléctionnés',
	searchAppelTypeent:	'<b>type d\'entreprise</b><br/>Seul les appels passés à une entreprise de ce type seront séléctionnés',
	searchAppelOrder: 	'<b>Trier le résultat</b> en fonction du critère suivant',
	searchAppelPremierc:	'<b>Premier contact</b><br/>Seul les contacts n\'ayant eu qu\'un appel seront séléctionnés',
	searchAppelDep: 	'<b>Département du contact</b><br/>Seul les appels liés à une entreprise située dans ce département seront séléctionnés',
	searchAppelFonction:	'<b>Fonction du contact</b><br/>Seul les appels liés à un contact ayant cette fonction seront séléctionnés',
	appelDate:		'<b>Date de l\'appel</b><br/>Date à laquelle cet appel à été effectué',
	appelRappel:		'<b>Relance</b><br/>Cocher cette case si cet appel doit donner lieu à un rappel',
	appelRappelD:		'<b>Date de rappel</b><br/>Date à laquelle vous souhaitez rappeler ',
	appelRappelH:		'<b>Heure de rappel</b><br/>Heure à laquelle vous souhaitez rappeler votre contact ',
	appelProjet:		'<b>Rattacher un projet</b><br/>Vous pouvez lier cet appel à un projet existant. Pour cela, saisissez le titre du projet ou le nom de l\'entreprise pour voir apparaitre la liste des projets correspondants. ',
	appelAffaire:		'<b>Rattacher une affaire</b><br/>Vous pouvez lier cet appel à une affaire existante. Pour cela, saisissez le titre de l\'affaire ou le nom de l\'entreprise pour voir apparaitre la liste des affaires correspondantes. ',
	appelComment:		'Commentaire de votre appel'
    } ,
  
    projets: {
	titre:		 	'Titre du projet.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à ce projet',
	type:			'Quel est le type de ce projet',
	contact:		'Vous devez saisir le nom du contact principal de ce projet. Il est préférable de choisir le décideur comme contact principal.',
	dateRdv:		'Date du rendez-vous de ce projet',
	heureRdv:		'Heure à la quelle le RDV projet à été convenu',
	budget:			'Quel est le budget estimé de ce projet.',
	desc:			'Commentaire de votre projet'
    } ,
    

    affaire: {
	searchIC: 		'Restreindre la recherche aux affaires gérées par un <b>commercial</b> en particulier',
	searchRegion: 		'Restreindre la recherche aux affaires dont le <b>code postal</b> du client commence par',
	searchID: 		'Restreindre la recherche aux affaires dont <b>l\'identifiant</b> commence par',
	searchEntreprise: 	'Restreindre la recherche aux affaires dont le <b>client est</b>',
	searchTitre: 		'Restreindre la recherche aux affaires dont le <b>titre contient</b>',
	searchArchive: 		'Restreindre la recherche aux <b>affaires archivées</b>. <br/>Si cette option est désactivée, la recherche ne s\'applique qu\'aux affaires actives',
	searchStatut: 		'Restreindre la recherche aux affaires dont le <b>statut</b> est le suivant',
	searchEcheance: 	'Restreindre la recherche aux affaires ayant une <b>date d\'écheance</b> inférieure à',
	searchType: 		'Restreindre la recherche aux affaires dont le <b>type</b> correspond au type suivant',
	titre:		 	'Titre de l\'affaire.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à cette affaire',
	type:			'Type de l\'affaire. permet de regrouper les affaires par famille',
	actif:			'Une affaire est par defaut active. Si vous souhaitez désactiver une affaire, elle ne sera plus présente dans les moteurs de recherches. ',
	contact:		'Choisissez le nom du commercial en charge de cette affaire',
	statut:			'Vous permet de connaitre l\'état de cette affaire. le statut d\'une affaire évolue tout seul en fonction des actions qui ont été menées (création de devis, enregistrement de commande, émission de facture,...)',
	echeance:		'Indique l\'écheance attendue pour la concrétisation de cette affaire. Passée cette écheance, l\'affaire sera mise en avant dans vos recherches',
	projet:			'indique si un projet est lié à cette affaire, et vous permet de consulter les informations de ce projet',
	budget:			'Quel est le budget estimé de cette affaire. Lorsque vous créez des devis en relation avec une affaire, ce montant est automatiquement mis à jour<br/>. S\'il y a plusieurs devis, la moyenne de leurs valeurs est alors attribuée.',
	decideur:		'Saisissez la personne en charge de cette affaire chez votre client',
	description:		'Description de votre projet',
	commentaire:		'Commentaire de votre projet'
    
    } ,
  
    devis: {
	addEntAff:		'Vous devez saisir les 2 premiers caractères du nom d\'une entreprise ou du titre d\'une affaire.<br/>Choisissez parmis la liste qui s\'affiche le résultat qui vous convient.',
	bdcclient:		'Numero de bon de commande fournit par le client.<br/> Ce numero est en général saisi lors de la récéption du bon de commande client',
	cmdRenew: 		'Souhaitez-vous programmer un renouvellement automatique de ce devis.<br/>En cochant cette option, et en définissant un cycle, le devis apparaitra dans le tableau des renouvellement, et vous pourrez facilement créer une nouvelle proposition en repartant de ses éléments.',
	cmdRenewCycle: 		'A quelle fréquence souhaitez vous effectuer le renouvellement de ce devis ?',
	commentaire:		'Commentaire de ce devis',
	commercial:		'Choisissez le nom du commercial en charge de ce devis. Par defaut, c\'est l\'utilisateur ayant créé le devis qui est enregistré',
	contactTech:		'Vous devez saisir le nom du contact commercial de ce devis. Il est préférable de choisir le contact principal avec lequel vous traitez cette affaire',
	contactAchat:		'Vous devez saisir le nom du contact achat de ce devis. Ce contact sera utilisé lors de la facturation, comme destinataire de la facture',
	cree:		 	'Date de création du devis',
	deliveryNom:		'Nom de l\'entreprise ou du contact de ce devis. Ce nom est utilisé dans toutes les correspondances vers le client',
	deliveryCpVille: 	'Saississez le <b>code postal</b> de l\'entreprise.<br/> Le <b>nom de la ville</b> apparait automatiquement. Vous pouvez cependant modifier la ville proposée, en modifiant le champ ville.',
	deliveryAdd: 		'<b>Adresse de l\'entreprise</b>. Ce champ est utilisé pour toute communication courrier avec cette entreprise.<br/>Veillez à saisir correctement les informations qui vous ont été transmises.',
	deliveryPays: 		'<b>Pays</b> de domiciliation de l\'entreprise',
	deliveryComplement:	'Complement d\'information sur l\'envoi du devis',
	deliveryMail:		'Adresse e-mail utilisée pour l\'envoi du devis et toutes autre corespondance relative à ce dernier.',
	entreprise:		'Nom de l\'entreprise liée à ce devis.<br/> Ce champs est rempli autotmatiquement à partir des informations de l\'affaire',
	generateCannevas:	'Modèle de document à utiliser pour la création du fichier devis.<br/>Cette option n\'est utile que si vous souhaitez "générer" ou "enregistrer" votre document',
	generateOutput:		'Format de sortie du document.<br/>Cette option n\'est utile que si vous souhaitez "générer" ou "enregistrer" votre document',
	modifie:		'Date de modification du devis',
	searchAff: 		'Restreindre la recherche aux devis dont la référence commence par',
	searchBudgMin: 		'Restreindre la recherche aux devis ayant un budget supérieur à',
	searchBudgMax: 		'Restreindre la recherche aux devis ayant un budget inférieur à',
	searchComm: 		'Restreindre la recherche aux devis gérées par un <b>commercial</b> en particulier',
	searchCP: 		'Restreindre la recherche aux devis dont le <b>département</b> du client est',
	searchEnt: 		'Restreindre la recherche aux devis dont le <b>client est</b>',
	searchStatut: 		'Restreindre la recherche aux devis dont le <b>statut</b> est le suivant',
	searchTitre: 		'Restreindre la recherche aux devis dont le <b>titre contient</b>',
	sendAdd:		'Adresse utilisée pour l\'envoi postal',
	sendComplement:		'Informations complémentaires sur l\'envoi postal',
	sendCpVille:		'Code postal et ville utilisés pour l\'envoi postal',
	sendCannevas:		'Liste des modèles de réponse type.<br/>Cette option vous permet de choisir parmis les différents messages type déjà enregistrés',
	sendDestinataire:	'Nom du destinataire de votre envoi',
	sendFax:		'Numéro de fax de destination.<br/>Vous devez respecter la syntaxe suivante:<br/>0145457878<br/>+33(1)45457878',
	sendMail:		'Adresse e-mail de destination du message.<br/>Pour expédier votre devis à plusieurs contacts, vous devez séparer leurs adresses par un ";"',
	sendMessage:		'Contenu de votre message<br/>Ce contenu est automatiquement actualisé lorsque vous utilisez un gabarit de message',
	sendPays:		'Pays utilisé pour l\'envoi postal',
	sendPJ:			'Pièce jointe de l\'envoi.<br/>Cette option n\'est utile que lors d\'un envoi par mail, fax ou courrier',
	sendSujet:		'Sujet de votre envoi.<br/>Cette option n\'est utile que lors d\'un envoi par mail ou par fax',
	sendType:		'Type d\'envoi que vous souhaitez réaliser.<br/>Cette option n\'est utile que si vous souhaitez "enregistrer & envoyer" ou "envoyer" votre document',
	tauxTva:		'Taux de TVA applicable à cette entreprise pour ce devis. Par defaut, corespond au taux de tva de l\'entreprise',
	titre:		 	'Titre du devis.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à ce devis',
	statut:			'Vous permet de connaitre l\'état de ce devis. le statut d\'un devis évolu tout seul en fonction des actions qui ont été menées'
    } ,
  
    commande: {
	bdcc:			'Vous permet d\'enregistrer le numéro de bon de commande fournit par votre client lors de sa commande.',
	commercial:		'Choisissez le nom du commercial en charge de cette commande.<br/>Par defaut, c\'est l\'utilisateur ayant créé cette commande qui est enregistré',
	contactTech:		'Vous devez saisir le nom du contact commercial de cette commande. Il est préférable de choisir le contact principal avec lequel vous traitez cette affaire.<br/>Par defaut, le contact technique du devis est automatiquement repris',
	contactAchat:		'Vous devez saisir le nom du contact achat de cette commande. Ce contact sera utilisé lors de la facturation, comme destinataire de la facture.<br/>Par defaut, le contact achat du devis est automatiquement repris',
	deliveryNom:		'Nom de l\'entreprise ou du contact de cette commande. Ce nom est utilisé dans toutes les correspondances vers le client',
	deliveryCpVille: 	'Saississez le <b>code postal</b> de l\'entreprise.<br/> Le <b>nom de la ville</b> apparait automatiquement. Vous pouvez cependant modifier la ville proposée, en modifiant le champ ville.',
	deliveryAdd: 		'<b>Adresse de l\'entreprise</b>. Ce champ est utilisé pour toute communication courrier avec cette entreprise.<br/>Veillez à saisir correctement les informations qui vous ont été transmises.',
	deliveryPays: 		'<b>Pays</b> de domiciliation de l\'entreprise',
	deliveryComplement:	'Complement d\'information sur l\'envoi de cette commande',
	deliveryMail:		'Adresse e-mail utilisée pour l\'envoi de cette commande et toutes autre corespondances relative à cette dernière.',
	entreprise:		'Nom de l\'entreprise liée à cette commande.<br/> Ce champs est rempli autotmatiquement à partir des informations du devis',
	generateOutput:		'Format de sortie du document.<br/>Cette option n\'est utile que si vous souhaitez "générer" ou "enregistrer" votre document',
	infoDateCree:		'Date de création de la commande',
	infoDateModif: 		'Date de la dernière modification faite  sur cette commande',
	infoTitre: 		'Titre de la commande.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à cette commande.<br/> Par defaut, le titre du devis est repris comme titre de la commande.',
	infoBDCC: 		'Numero de bon de commande fournit par le client.<br/> Ce numero est en général saisi lors de la création d\'une commande',
	nom:		 	'Titre de cette commande.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à cette commande.<br/>Par defaut, le titre du devis est saisi',
	reglementMode:		'Vous pouvez choisir un mode de règlement pour cette commande. Ce mode de règlement sera utilisé lors de la création de votre facture client',
	reglementCondi:		'Vous pouvez choisir les conditions de règlement de la facture client qui sera créée une fois la commande traitée.',
	searchAff: 		'Restreindre la recherche aux commandes dont la référence commence par',
	searchBudgMin: 		'Restreindre la recherche aux commandes ayant un budget supérieur à',
	searchBudgMax: 		'Restreindre la recherche aux commandes ayant un budget inférieur à',
	searchComm: 		'Restreindre la recherche aux commandes gérées par un <b>commercial</b> en particulier',
	searchCP: 		'Restreindre la recherche aux commandes dont le <b>département</b> du client est',
	searchEnt: 		'Restreindre la recherche aux commandes dont le <b>client est</b>',
	searchStatut: 		'Restreindre la recherche aux commandes dont le <b>statut</b> est le suivant',
	searchTitre: 		'Restreindre la recherche aux commandes dont le <b>titre contient</b>',
	sendAdd:		'Adresse utilisée pour l\'envoi postal',
	sendComplement:		'Informations complémentaires sur l\'envoi postal',
	sendCpVille:		'Code postal et ville utilisés pour l\'envoi postal',
	sendCannevas:		'Liste des modèles de réponse type.<br/>Cette option vous permet de choisir parmis les différents messages type déjà enregistrés',
	sendDestinataire:	'Nom du destinataire de votre envoi',
	sendFax:		'Numéro de fax de destination.<br/>Vous devez respecter la syntaxe suivante:<br/>0145457878<br/>+33(1)45457878',
	sendMail:		'Adresse e-mail de destination du message.<br/>Pour expédier votre commande à plusieurs contacts, vous devez séparer leurs adresses par un ";"',
	sendMessage:		'Contenu de votre message<br/>Ce contenu est automatiquement actualisé lorsque vous utilisez un gabarit de message',
	sendPays:		'Pays utilisé pour l\'envoi postal',
	sendPJ:			'Pièce jointe de l\'envoi.<br/>Cette option n\'est utile que lors d\'un envoi par mail, fax ou courrier',
	sendSujet:		'Sujet de votre envoi.<br/>Cette option n\'est utile que lors d\'un envoi par mail ou par fax',
	sendType:		'Type d\'envoi que vous souhaitez réaliser.<br/>Cette option n\'est utile que si vous souhaitez "enregistrer & envoyer" ou "envoyer" votre document',
	sendCopyToMe:		'Pour recevoir une copie du document envoyé, directement dans votre boite mail',
	statut:			'Vous permet de connaitre l\'état de cette commande. le statut d\'une commande évolue tout seul en fonction des actions qui ont été menées'
    } ,

    facture: {
	cmdOuEnt:		'Nom de l\'entreprise, ou numero du bon de commande, liée à cette facture.',
	nom:		 	'Titre de cette facture.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à cette facture.<br/>Par defaut, le titre du devis est saisi',
	bdcc:			'Vous permet d\'enregistrer le numéro de bon de commande fournit par votre client lors de sa commande.',
	reglementMode:		'Vous pouvez choisir un mode de règlement pour cette facture.',
	reglementCondi:		'Vous pouvez choisir les conditions de règlement de la facture client.',
	commentreglement:	'Commentaire interne sur le règlement de cette facture',
	infoDateCree:		'Date de création de la facture',
	infoDateModif: 		'Date de la dernière modification faite  sur cette facture',
	infoDateReglement: 	'Date de règlement, prévu ou effective, pour cette facture',
	statut:			'Le statut de cette facture',
	infoTitre: 		'Titre de la facture.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à cette facture.<br/> Par defaut, le titre de la commande est repris comme titre de la facture.',
	infoBDCC: 		'Numero de bon de facture fournit par le client.<br/> Ce numero est en général saisi lors de la création d\'une facture',
	infotauxTva:		'Taux de TVA applicable à cette entreprise pour cette facture. Par defaut, corespond au taux de tva de l\'entreprise',
	entreprise:		'Nom de l\'entreprise liée à cette facture.<br/> Ce champs est rempli autotmatiquement à partir des informations du devis ou de la commande',
	commercial:		'Choisissez le nom du commercial en charge de cette facture.<br/>Par defaut, c\'est l\'utilisateur ayant créé cette facture qui est enregistré',
	contactTech:		'Vous devez saisir le nom du contact commercial de cette facture. Il est préférable de choisir le contact principal avec lequel vous traitez cette affaire.<br/>Par defaut, le contact technique du devis est automatiquement repris',
	contactAchat:		'Vous devez saisir le nom du contact achat de cette facture. Ce contact sera utilisé lors de la facturation, comme destinataire de la facture.<br/>Par defaut, le contact achat du devis est automatiquement repris',
	deliveryNom:		'Nom de l\'entreprise ou du contact de cette facture. Ce nom est utilisé dans toutes les correspondances vers le client',
	deliveryCpVille: 	'Saississez le <b>code postal</b> de l\'entreprise.<br/> Le <b>nom de la ville</b> apparait automatiquement. Vous pouvez cependant modifier la ville proposée, en modifiant le champ ville.',
	deliveryAdd: 		'<b>Adresse de l\'entreprise</b>. Ce champ est utilisé pour toute communication courrier avec cette entreprise.<br/>Veillez à saisir correctement les informations qui vous ont été transmises.',
	deliveryPays: 		'<b>Pays</b> de domiciliation de l\'entreprise',
	deliveryMail:		'Adresse e-mail utilisée pour l\'envoi de cette facture et toutes autre corespondances relative à cette dernière.',
	renewActiver:		'Active le renouvellement automatique de cette facture à une intervalle de temps que vous définissez<br/> Cette action entraine la création d\'une nouvelle facture, reprenant les éléments de la facture d\'origine',
	renewFrequence:		'Définit la fréquence à laquelle la facture doit être re-créer',
	renewDateFin:		'Permet de définir une date à partir de laquelle le renouvellement ne sera plus effectué',
	renewStatut:		'Défini le statut par defaut des factures qui sont automatiquement générées.',
	renewMail:		'Inscriver votre adresse e-mail pour recevoir une alerte lors de la création automatique d\'une facture',
	generateCannevas:	'Modèle de document à utiliser pour la création du fichier facture.<br/>Cette option n\'est utile que si vous souhaitez "générer" ou "enregistrer" votre document',
	generateOutput:		'Format de sortie du document.<br/>Cette option n\'est utile que si vous souhaitez "générer" ou "enregistrer" votre document',
	searchAff: 		'Restreindre la recherche aux factures dont la référence commence par',
	searchBudgMin: 		'Restreindre la recherche aux factures ayant un budget supérieur à',
	searchBudgMax: 		'Restreindre la recherche aux factures ayant un budget inférieur à',
	searchComm: 		'Restreindre la recherche aux factures gérées par un <b>commercial</b> en particulier',
	searchCP: 		'Restreindre la recherche aux factures dont le <b>département</b> du client est',
	searchEnt: 		'Restreindre la recherche aux factures dont le <b>client est</b>',
	searchStatut: 		'Restreindre la recherche aux factures dont le <b>statut</b> est le suivant',
	searchTitre: 		'Restreindre la recherche aux factures dont le <b>titre contient</b>',
	searchType: 		'Restreindre la recherche aux factures dont le <b>type est</b>',
	sendAdd:		'Adresse utilisée pour l\'envoi postal',
	sendComplement:		'Informations complémentaires sur l\'envoi postal',
	sendCpVille:		'Code postal et ville utilisés pour l\'envoi postal',
	sendCannevas:		'Liste des modèles de réponse type.<br/>Cette option vous permet de choisir parmis les différents messages type déjà enregistrés',
	sendDestinataire:	'Nom du destinataire de votre envoi',
	sendFax:		'Numéro de fax de destination.<br/>Vous devez respecter la syntaxe suivante:<br/>0145457878<br/>+33(1)45457878',
	sendMail:		'Adresse e-mail de destination du message.<br/>Pour expédier votre facture à plusieurs contacts, vous devez séparer leurs adresses par un ";"',
	sendMessage:		'Contenu de votre message<br/>Ce contenu est automatiquement actualisé lorsque vous utilisez un gabarit de message',
	sendPays:		'Pays utilisé pour l\'envoi postal',
	sendPJ:			'Pièce jointe de l\'envoi.<br/>Cette option n\'est utile que lors d\'un envoi par mail, fax ou courrier',
	sendSujet:		'Sujet de votre envoi.<br/>Cette option n\'est utile que lors d\'un envoi par mail ou par fax',
	sendType:		'Type d\'envoi que vous souhaitez réaliser.<br/>Cette option n\'est utile que si vous souhaitez "enregistrer & envoyer" ou "envoyer" votre document',
	sendCopyToMe:		'Pour recevoir une copie du document envoyé, directement dans votre boite mail'
    }  ,

    factFourn: {
	contact:		'Nom du contact chez votre fournisseur',
	desc:			'Déscription de la facture. Cette déscription vous permet de saisir des commentaires sur la facture',
	dateReglementAttendu:	'Date de règlement attendu pour cette facture.',
	fournisseur:	 	'Nom du fournisseur associé à cette facture',
	montantHT:		'Montant HT de la facture.<br/> Ce champs est automatiquement mis à jour.',
	montantTTC:		'Montant TTC de la facture',
	nom:		 	'Titre de cette facture.<br/>Nous vous conseillons de saisir une phrase courte et explicite, contenant les principaux mots clefs applicables à cette facture.',
	reglementMode:		'Vous pouvez choisir un mode de règlement pour cette facture.',
	renewActiver:		'Active le renouvellement automatique de cette facture à une intervalle de temps que vous définissez<br/> Cette action entraine la création d\'une nouvelle facture, reprenant les éléments de la facture d\'origine',
	renewFrequence:		'Définit la fréquence à laquelle la facture doit être re-créer',
	renewDateFin:		'Permet de définir une date à partir de laquelle le renouvellement ne sera plus effectué',
	renewStatut:		'Défini le statut par defaut des factures qui sont automatiquement générées.',
	renewMail:		'Inscriver votre adresse e-mail pour recevoir une alerte lors de la création automatique d\'une facture',
	statut:			'Statut de la facture',
	searchContact: 		'Restreindre la recherche aux factures dont le <b>contact client</b> est',
	searchEnt: 		'Restreindre la recherche aux factures dont le <b>fournisseur est</b>',
	searchMontantMin: 	'Restreindre la recherche aux factures ayant un montant supérieur à',
	searchMontantMax: 	'Restreindre la recherche aux factures ayant un montant inférieur à',
	searchStatut: 		'Restreindre la recherche aux factures dont le <b>statut</b> est le suivant',
	searchTitre: 		'Restreindre la recherche aux factures dont le <b>titre contient</b>',
	tauxTVA:		'Taux de TVA applicable sur cette facture'
    }  ,

    produit: {
	bestsell:		'Les produits "best Seller" apparaissent en tête de liste de vos résultats. Ils sont ainsi plus rapidement accéssibles',
	desc:			'Déscription de votre produit. Cette déscription sera automatiquement ajoutée dans vos devis, commandes et factures, lors de leurs création',
	famille:		'Famille du produit.<br/> vous pouvez ajouter une famille a l\'aide du bouton "+"',
	fournPxPub:		'Prix public au catalogue du fournisseur',
	fournRemise:		'Pourcentage de remise accordé par ce fournisseur.<br/>Ce champs est automatiquement rempli d\'après les informations du fournisseur',
	fournPxAchat:		'Prix d\'achat de ce produit après de ce fournisseur.<br/>Ce prix est automatiquement calculé d\'après le prix public et le taux de remise qui vous est accordé par ce fournisseur',
	fournDisable:		'Désactive la possibilité d\'utiliser ce fournisseur pour l\'achat de ce produit.</br>Vous devez dabord désactiver ce fournisseur, pour ce produit, avant de pouvoir supprimer l\'association produit-fournisseur',
	fournEnable:		'Re-active la possibilité d\'utiliser ce fournisseur pour l\'achat de ce produit',
	fournDelete:		'Supprime définitivement la possibilité de commander ce produit auprès de ce fournisseur.',
	fournEntreprise:	'Nom de votre fournisseur',
	nom:			'Titre du produit',
	prix:			'Prix HT du produit. Le calcul de la TVA sera faite en fonction de vos clients ou de vos fournisseurs',
	reference:		'Référence du produit',
	renew:			'Durée de renouvellement de ce produit vis à vis de vos clients.<br/> Lorsqu\'un produit est renouvellable, Il apparait dans la gestion des devis à renouveller. Une alerte vous informant de l\'écheance vous parviendra par mail.',
	stillAvailable:		'Disponibilité du produit. Lorsque cette case est décochée, les produits ne sont plus disponible dans votre instance. Vous conservez une trace de cette référence, mais elle n\'est plus disponible à la vente',
	stock:			'Quantité de produits en stock. Vous pourez alors utiliser ce stock lors de vos commandes clients.',
	searchReference:	'Référence du/des produit(s) recherché(s)',
	searchNom:		'Nom du/des produit(s) recherché(s)',
	searchFamille:		'Famille du/des produit(s) recherché(s)',
	searchFournisseur:	'Nom du fournisseur du/des produit(s) recherché(s)',
	searchDisponible:	'Le produit recherché est-il disponible en stock',
	searchPrixMin:		'Prix minimum des produits recherchés',
	searchPrixMax:		'Prix maximum des produits recherchés'
    }  ,

    fournisseur: {
	actif:			'Lorsqu\'un fournisseur est désactivé, il ne peux plus fournir de produit lors de vos commandes. </br>Vous devez dabord désactiver ce fournisseur avant de pouvoir le supprimer',
	commercial:		'Choisissez le nom du commercial en charge de cette facture.<br/>Par defaut, c\'est l\'utilisateur ayant créé cette facture qui est enregistré',
	remise:                 'La remise habituelle de ce fournisseur sur ses produits',
        contactAdv:		'Contact responsable de la gestion de vos commandes chez votre fournisseur',
	contactFacturation:	'Contact responsable de la facturation chez votre fournisseur',
	searchReference:	'Référence du/des fournisseur(s) recherché(s)',
	searchNom:		'Nom du/des fournisseurs(s) recherché(s)',
	searchCP:		'Département du/des fournisseur(s) recherché(s)',
	searchContact:		'Nom du contact chez vos fournisseurs recherché(s)',
	searchActif:		'Le fournisseur recherché est-il actif',
	produitNewPrix:		'Saisissez un nouveau prix a appliquer sur l\'ensemble des produits séléctionnés',
	produitNewRemise:	'Saisissez une nouvelle remise a appliquer sur l\'ensemble des produits séléctionnés'
    }  ,

    pontComptable: {
	reference:		    'Identifiant unique du fichier généré',
	nom:			    'Résumé du fichier d\'échange',
	date:			    'Date de création du fichier',
	config_dateDebut:	    'Date de début de la recherche',
	config_dateFin:		    'Date de fin de la recherche',
	hasFactureClient:	    'Ce fichier doit-il inclure les factures clients. En cochant cette case, vous ajoutez les factures clients dans le fichier d\'export.<br/>Veuillez à bien choisir les status de facture autorisés',
	config_statutFact:	    'Vous devez choisir les statuts de facture qui seront autorisés dans le fichier d\'export',
	hasFactureFourn:	    'Ce fichier doit-il inclure les factures fournisseurs. En cochant cette case, vous ajoutez les factures fournisseurs dans le fichier d\'export.<br/>Veuillez à bien choisir les status de facture fournisseurs autorisés',
	config_statutFactFourn:	    'Vous devez choisir les statuts de facture fournisseur qui seront autorisés dans le fichier d\'export',
	groupActionDelete:	    'Suppression du lot de fichiers d\'export',
	groupActionChangeAttribute: 'Changer un attribut pour tout le lot de fichier d\'export',
	groupActionDeleteWithFile:  'Cocher cette case pour supprimer les fichiers d\'export du Disque Dur Virtuel',
	searchDateStart:	    'Date de génération du fichier. Si une date de fin est définie, ce champs sera la date de démarage de votre période de recherche',
	searchDateEnd:		    'Date de fin de génération du fichier. Si aucune date de début n\'est définie, tous les fichiers générés jusqu\'à cette date seront retournés.',
	searchNom:		    'Vous pouvez saisir un mot ou une phrase pour trouver tous les fichiers contenant votre saisie'
    }
};